<?php
$tests = array (
  'a_01a' =>
  array (
    'type' => 'true',
    'elem' => 'a',
    'test' => 'aSkipFirst',
    'score' => '10',
    'level' => 'a',
    'trust' => '0.7',
    'weight' => '0.8',
    'ref' => 'G1',
    'scs' => '2.4.1',
    'rel' => 'G124',
    'wcag' => '2',
  ),
  'a_01b' =>
  array (
    'type' => 'fals',
    'elem' => 'a',
    'test' => 'aSkipFirst',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'G1',
    'scs' => '2.4.1',
    'rel' => 'G124',
    'wcag' => '2',
  ),
  'a_02a' =>
  array (
    'type' => 'fals',
    'elem' => 'a',
    'test' => 'aSkip',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'top' => '10',
    'ref' => 'G123',
    'scs' => '2.4.1',
    'rel' => 'G124',
    'wcag' => '3',
    'chkp' => '13.6',
    'curric' => 'sam104-0.htm',
    'prio' => 'aaa',
  ),
  'a_02b' =>
  array (
    'type' => 'true',
    'elem' => 'a',
    'test' => 'aSkip',
    'score' => '10',
    'level' => 'a',
    'trust' => '0.7',
    'weight' => '0.8',
    'ref' => 'G123',
    'scs' => '2.4.1',
    'rel' => 'G124',
    'wcag' => '3',
    'chkp' => '13.6',
    'curric' => 'sam104-0.htm',
    'prio' => 'aaa',
  ),
  'a_03' =>
  array (
    'type' => 'decr',
    'elem' => 'a',
    'test' => 'aImgAltNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'top' => '1',
    'steps' => '1',
    'ref' => 'F89',
    'scs' => '2.4.4,2.4.9,4.1.2',
    'rel' => 'H30',
    'wcag' => '3',
    'chkp' => '13.1',
    'curric' => 'sam97-0.htm',
    'prio' => 'AA',
  ),
  'a_04' =>
  array (
    'type' => 'fals',
    'elem' => 'all',
    'test' => 'a',
    'score' => '3',
    'level' => 'AA',
    'trust' => '1',
    'weight' => '0.5',
    'ref' => 'G125',
    'scs' => '2.4.5',
    'wcag' => '2',
  ),
  'a_05' =>
  array (
    'type' => 'prop',
    'elem' => 'a',
    'test' => 'aTitleMatch',
    'score' => '5',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'ref' => 'H33',
    'scs' => '2.4.4,2.4.9',
    'wcag' => '2',
  ),
  'a_06' =>
  array (
    'type' => 'decr',
    'elem' => 'a',
    'test' => 'aAdjacentSame',
    'score' => '5',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'top' => '1',
    'steps' => '1',
    'ref' => 'H2',
    'scs' => '1.1.1,2.4.4,2.4.9',
    'wcag' => '2',
  ),
  'a_07' =>
  array (
    'type' => 'decr',
    'elem' => 'a',
    'test' => 'aGroupNo',
    'score' => '5',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'top' => '1',
    'steps' => '1',
    'ref' => 'H50',
    'scs' => '2.4.1',
    'wcag' => '3',
    'chkp' => '13.5',
    'curric' => 'sam103-0.htm',
    'prio' => 'aaa',
  ),
  'a_08' =>
  array (
    'type' => 'decr',
    'elem' => 'a',
    'test' => 'aJs',
    'score' => '4',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'top' => '1',
    'steps' => '1',
    'wcag' => '1',
    'chkp' => '6.3',
    'curric' => 'sam56-0.htm',
    'prio' => 'A',
  ),
  'a_09' =>
  array (
    'type' => 'decr',
    'elem' => 'a',
    'test' => 'aSameText',
    'score' => '4',
    'level' => 'AAA',
    'trust' => '1',
    'weight' => '0.1',
    'top' => '2',
    'steps' => '2',
    'ref' => 'F84',
    'scs' => '2.4.9',
    'wcag' => '3',
    'chkp' => '13.1',
    'curric' => 'sam97-0.htm',
    'prio' => 'AA',
  ),
  'a_10' =>
  array (
    'type' => 'decr',
    'elem' => 'a',
    'test' => 'aAdjacent',
    'score' => '4',
    'level' => 'AAA',
    'trust' => '1',
    'weight' => '0.1',
    'top' => '2',
    'steps' => '2',
    'wcag' => '1',
    'chkp' => '10.5',
    'curric' => 'sam82-0.htm',
    'prio' => 'AAA',
  ),
  'abbr_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'abbrNo',
    'score' => '3',
    'level' => 'AAA',
    'trust' => '1',
    'weight' => '0.1',
    'ref' => 'G102',
    'scs' => '3.1.4',
    'rel' => 'H28',
    'wcag' => '3',
    'chkp' => '4.2',
    'curric' => 'sam41-0.htm',
    'prio' => 'aaa',
  ),
  'akey_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'acckeyRep',
    'score' => '4',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'ref' => 'F17',
    'scs' => '1.3.1,4.1.1',
    'wcag' => '3',
    'chkp' => '9.5',
    'curric' => 'sam76-0.htm',
    'prio' => 'aaa',
  ),
  'applet_01' =>
  array (
    'type' => 'prop',
    'elem' => 'applet',
    'test' => 'appletAltNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H35',
    'scs' => '1.1.1',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam8-0.htm',
    'prio' => 'A',
  ),
  'area_01a' =>
  array (
    'type' => 'fals',
    'elem' => 'area',
    'test' => 'areaAltNo',
    'score' => '10',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'ref' => 'H24',
    'scs' => '1.1.1,2.4.4,2.4.9',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam6-0.htm',
    'prio' => 'A',
  ),
  'area_01b' =>
  array (
    'type' => 'prop',
    'elem' => 'area',
    'test' => 'areaAltNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F65',
    'scs' => '1.1.1',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam6-0.htm',
    'prio' => 'A',
  ),
  'blink_01' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'blink',
    'score' => '2',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'top' => '1',
    'steps' => '1',
    'ref' => 'F47',
    'scs' => '2.2.2',
    'wcag' => '3',
    'chkp' => '7.2',
    'curric' => 'sam61-0.htm',
    'prio' => 'aa',
  ),
  'blink_02' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'cssBlink',
    'score' => '3',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'ref' => 'F4',
    'scs' => '2.2.2',
    'rel' => 'SCR22',
    'wcag' => '3',
    'chkp' => '7.2',
    'curric' => 'sam61-0.htm',
    'prio' => 'aa',
  ),
  'br_01' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'brSec',
    'score' => '3',
    'level' => 'a',
    'trust' => '0.7',
    'weight' => '0.9',
    'top' => '1',
    'steps' => '1',
    'ref' => 'H48',
    'scs' => '1.3.1',
    'wcag' => '2',
  ),
  'color_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'colorFgBgNo',
    'score' => '5',
    'level' => 'aa',
    'trust' => '0.9',
    'weight' => '0.4',
    'top' => '1',
    'steps' => '1',
    'ref' => 'F24',
    'scs' => '1.4.3,1.4.6,1.4.8',
    'wcag' => '2',
  ),
  'color_02' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'colorContrast',
    'score' => '4',
    'level' => 'aa',
    'trust' => '0.8',
    'weight' => '0.4',
    'top' => '1',
    'steps' => '1',
    'ref' => 'G145',
    'scs' => '1.4.3',
    'wcag' => '2',
  ),
  'css_01' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'lineHeightNo',
    'score' => '3',
    'level' => 'aaa',
    'trust' => '0.8',
    'weight' => '0.1',
    'top' => '1',
    'steps' => '1',
    'ref' => 'C21',
    'scs' => '1.4.8',
    'wcag' => '2',
  ),
  'css_validator_01' =>
  array (
    'type' => 'fals',
    'elem' => 'cssValidator',
    'test' => 'cssValidatorErrors',
    'score' => '10',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'ref' => 'G134',
    'scs' => '4.1.1',
    'wcag' => '3',
    'chkp' => '3.2',
    'curric' => 'sam29-0.htm',
    'prio' => 'AA',
  ),
  'css_validator_02' =>
  array (
    'type' => 'decr',
    'elem' => 'cssValidator',
    'test' => 'cssValidatorErrors',
    'score' => '5',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'top' => '3',
    'steps' => '3',
    'ref' => 'G134',
    'scs' => '4.1.1',
    'wcag' => '3',
    'chkp' => '3.2',
    'curric' => 'sam29-0.htm',
    'prio' => 'AA',
  ),
  'deprec_01a' =>
  array (
    'type' => 'fals',
    'elem' => 'all',
    'test' => 'deprecElem',
    'score' => '10',
    'level' => 'AA',
    'trust' => '1',
    'weight' => '0.5',
    'wcag' => '1',
    'chkp' => '11.2',
    'curric' => 'sam87-0.htm',
    'prio' => 'AA',
  ),
  'deprec_01b' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'deprecElem',
    'score' => '5',
    'level' => 'AA',
    'trust' => '1',
    'weight' => '0.5',
    'top' => '2',
    'steps' => '2',
    'wcag' => '1',
    'chkp' => '11.2',
    'curric' => 'sam87-0.htm',
    'prio' => 'AA',
  ),
  'deprec_02a' =>
  array (
    'type' => 'fals',
    'elem' => 'all',
    'test' => 'deprecAttr',
    'score' => '10',
    'level' => 'AA',
    'trust' => '0.9',
    'weight' => '0.5',
    'wcag' => '1',
    'chkp' => '11.2',
    'curric' => 'sam87-0.htm',
    'prio' => 'AA',
  ),
  'deprec_02b' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'deprecAttr',
    'score' => '5',
    'level' => 'AA',
    'trust' => '1',
    'weight' => '0.5',
    'top' => '3',
    'steps' => '3',
    'wcag' => '1',
    'chkp' => '11.2',
    'curric' => 'sam87-0.htm',
    'prio' => 'AA',
  ),
  'dtd_01' =>
  array (
    'type' => 'fals',
    'elem' => 'all',
    'test' => 'dtd',
    'score' => '3',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'ref' => 'H88',
    'scs' => '4.1.1,4.1.2',
    'wcag' => '3',
    'chkp' => '3.2',
    'curric' => 'sam29-0.htm',
    'prio' => 'AA',
  ),
  'dtd_02' =>
  array (
    'type' => 'true',
    'elem' => 'dtd',
    'test' => 'dtdOld',
    'score' => '5',
    'level' => 'AA',
    'trust' => '0.9',
    'weight' => '0.4',
    'wcag' => '1',
    'chkp' => '11.1',
    'curric' => 'sam83-0.htm',
    'prio' => 'aa',
  ),
  'ehandler_01' =>
  array (
    'type' => 'true',
    'elem' => 'ehandler',
    'test' => 'ehandMouse',
    'score' => '1',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F54',
    'scs' => '2.1.1',
    'wcag' => '3',
    'chkp' => '6.4',
    'curric' => 'sam57-0.htm',
    'prio' => 'AA',
  ),
  'ehandler_02' =>
  array (
    'type' => 'prop',
    'elem' => 'ehandler',
    'test' => 'ehandBothNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'SCR20',
    'scs' => '2.1.1,2.1.3',
    'rel' => 'G90',
    'wcag' => '3',
    'chkp' => '6.4',
    'curric' => 'sam57-0.htm',
    'prio' => 'AA',
  ),
  'ehandler_03' =>
  array (
    'type' => 'true',
    'elem' => 'ehandler',
    'test' => 'ehandBoth',
    'score' => '10',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'ref' => 'G90',
    'scs' => '2.1.1,2.1.3',
    'rel' => 'SCR2,SCR20,SCR35',
    'wcag' => '3',
    'chkp' => '6.4',
    'curric' => 'sam57-0.htm',
    'prio' => 'AA',
  ),
  'ehandler_04' =>
  array (
    'type' => 'prop',
    'elem' => 'ehandler',
    'test' => 'ehandTagNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '0.8',
    'weight' => '0.9',
    'ref' => 'F59',
    'scs' => '4.1.2',
    'rel' => 'F42',
    'wcag' => '2',
  ),
  'embed_01' =>
  array (
    'type' => 'prop',
    'elem' => 'embed',
    'test' => 'embedAltNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'ref' => 'H46',
    'scs' => '1.1.1,1.2.8',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam8-0.htm',
    'prio' => 'A',
  ),
  'field_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'fieldLegNo',
    'score' => '4',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'ref' => 'H71',
    'scs' => '1.3.1,3.3.2',
    'wcag' => '2',
  ),
  'field_02' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'fieldNoForm',
    'score' => '3',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'top' => '1',
    'steps' => '1',
    'ref' => 'H71',
    'scs' => '1.3.1,3.3.2',
    'wcag' => '2',
  ),
  'flash' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'flash',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'wcag' => '1',
    'chkp' => '11.4',
    'curric' => 'sam90-0.htm',
    'prio' => 'A',
  ),
  'focus_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'focusBlur',
    'score' => '3',
    'level' => 'a',
    'trust' => '0.8',
    'weight' => '0.8',
    'ref' => 'F55',
    'scs' => '2.1.1,2.4.7,3.2.1',
    'wcag' => '2',
  ),
  'font_01' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'fontHtml',
    'score' => '4',
    'level' => 'AA',
    'trust' => '1',
    'weight' => '0.6',
    'top' => '1',
    'steps' => '1',
    'ref' => 'C22',
    'scs' => '1.3.1,1.4.4,1.4.5,1.4.9',
    'wcag' => '2',
  ),
  'font_02' =>
  array (
    'type' => 'prop',
    'elem' => 'fontValues',
    'test' => 'fontAbsVal',
    'score' => '4',
    'level' => 'AA',
    'trust' => '1',
    'weight' => '0.6',
    'ref' => 'C12',
    'scs' => '1.4.4',
    'rel' => 'C13,C14',
    'wcag' => '3',
    'chkp' => '3.4',
    'curric' => 'sam32-0.htm',
    'prio' => 'AA',
  ),
  'form_01a' =>
  array (
    'type' => 'fals',
    'elem' => 'form',
    'test' => 'formSubmitNo',
    'score' => '10',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'ref' => 'H32',
    'scs' => '3.2.2',
    'rel' => 'G80',
    'wcag' => '2',
  ),
  'form_01b' =>
  array (
    'type' => 'prop',
    'elem' => 'form',
    'test' => 'formSubmitNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'ref' => 'H32',
    'scs' => '3.2.2',
    'rel' => 'G80',
    'wcag' => '2',
  ),
  'frame_01' =>
  array (
    'type' => 'prop',
    'elem' => 'frame',
    'test' => 'frameTitleNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'ref' => 'H64',
    'scs' => '2.4.1,4.1.2',
    'wcag' => '3',
    'chkp' => '12.1',
    'curric' => 'sam91-0.htm',
    'prio' => 'A',
  ),
  'frame_02' =>
  array (
    'type' => 'true',
    'elem' => 'frameset',
    'test' => 'frameDtdNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'ref' => 'H88',
    'scs' => '4.1.1,4.1.2',
    'wcag' => '2',
  ),
  'hx_01a' =>
  array (
    'type' => 'fals',
    'elem' => 'all',
    'test' => 'hx',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H42',
    'scs' => '1.3.1',
    'rel' => 'G141',
    'wcag' => '3',
    'chkp' => '3.5',
    'curric' => 'sam33-0.htm',
    'prio' => 'AA',
  ),
  'hx_01b' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'hx',
    'score' => '10',
    'level' => 'aaa',
    'trust' => '0.9',
    'weight' => '0.1',
    'ref' => 'G141',
    'scs' => '1.3.1,2.4.10',
    'rel' => 'H42',
    'wcag' => '3',
    'chkp' => '3.5',
    'curric' => 'sam33-0.htm',
    'prio' => 'AA',
  ),
  'hx_01c' =>
  array (
    'type' => 'fals',
    'elem' => 'hx',
    'test' => 'h1',
    'score' => '4',
    'level' => 'aaa',
    'trust' => '1',
    'weight' => '0.1',
    'ref' => 'G141',
    'scs' => '1.3.1,2.4.10',
    'wcag' => '3',
    'chkp' => '3.5',
    'curric' => 'sam33-0.htm',
    'prio' => 'aa',
  ),
  'hx_02' =>
  array (
    'type' => 'true',
    'elem' => 'hx',
    'test' => 'hxNo',
    'score' => '3',
    'level' => 'AA',
    'trust' => '1',
    'weight' => '0.5',
    'ref' => 'G130',
    'scs' => '2.4.6',
    'wcag' => '3',
    'chkp' => '3.5',
    'curric' => 'sam33-0.htm',
    'prio' => 'AA',
  ),
  'hx_03' =>
  array (
    'type' => 'prop',
    'elem' => 'hx',
    'test' => 'hxSkip',
    'score' => '3',
    'level' => 'AAA',
    'trust' => '1',
    'weight' => '0.1',
    'ref' => 'G141',
    'scs' => '1.3.1,2.4.10',
    'rel' => 'H42',
    'wcag' => '3',
    'chkp' => '3.5',
    'curric' => 'sam33-0.htm',
    'prio' => 'AA',
  ),
  'id_01' =>
  array (
    'type' => 'true',
    'elem' => 'id',
    'test' => 'idRep',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F77',
    'scs' => '4.1.1',
    'rel' => 'F17',
    'wcag' => '2',
  ),
  'iframe_01' =>
  array (
    'type' => 'prop',
    'elem' => 'iframe',
    'test' => 'iframeTitleNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'ref' => 'H64',
    'scs' => '2.4.1,4.1.2',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam11-0.htm',
    'prio' => 'A',
  ),
  'img_01a' =>
  array (
    'type' => 'fals',
    'elem' => 'img',
    'test' => 'imgAltNo',
    'score' => '10',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'ref' => 'H37',
    'scs' => '1.1.1',
    'rel' => 'H45',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam2-0.htm',
    'prio' => 'A',
  ),
  'img_01b' =>
  array (
    'type' => 'prop',
    'elem' => 'img',
    'test' => 'imgAltNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F65',
    'scs' => '1.1.1',
    'rel' => 'H67',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam2-0.htm',
    'prio' => 'A',
  ),
  'img_02' =>
  array (
    'type' => 'prop',
    'elem' => 'img',
    'test' => 'imgAltNull',
    'score' => '8',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'ref' => 'C9',
    'scs' => '1.1.1',
    'rel' => 'F3',
    'wcag' => '2',
  ),
  'img_03' =>
  array (
    'type' => 'decr',
    'elem' => 'img',
    'test' => 'imgAltNot',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'top' => '1',
    'steps' => '1',
    'ref' => 'F30',
    'scs' => '1.1.1,1.2.1',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam2-0.htm',
    'prio' => 'A',
  ),
  'img_04' =>
  array (
    'type' => 'prop',
    'elem' => 'img',
    'test' => 'imgAltLong',
    'score' => '5',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'ref' => 'H45',
    'scs' => '1.1.1',
    'wcag' => '2',
  ),
  'inp_img_01a' =>
  array (
    'type' => 'fals',
    'elem' => 'inpImg',
    'test' => 'inpImgAltNo',
    'score' => '10',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'ref' => 'H36',
    'scs' => '1.1.1',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam2-0.htm',
    'prio' => 'A',
  ),
  'inp_img_01b' =>
  array (
    'type' => 'prop',
    'elem' => 'inpImg',
    'test' => 'inpImgAltNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F65',
    'scs' => '1.1.1',
    'wcag' => '3',
    'chkp' => '1.1',
    'curric' => 'sam2-0.htm',
    'prio' => 'A',
  ),
  'input_01' =>
  array (
    'type' => 'prop',
    'elem' => 'inputLabel',
    'test' => 'inputIdTitleNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'ref' => 'H65',
    'scs' => '1.1.1,1.3.1,3.3.2,4.1.2',
    'rel' => 'H44,G167',
    'wcag' => '2',
  ),
  'input_02' =>
  array (
    'type' => 'prop',
    'elem' => 'label',
    'test' => 'inputLabelNo',
    'score' => '3',
    'level' => 'a',
    'trust' => '0.8',
    'weight' => '0.9',
    'ref' => 'H44',
    'scs' => '1.1.1,1.3.1,3.3.2,4.1.2',
    'rel' => 'H65',
    'wcag' => '3',
    'chkp' => '12.4',
    'curric' => 'sam96-0.htm',
    'prio' => 'AA',
  ),
  'input_02b' =>
  array (
    'type' => 'fals',
    'elem' => 'inputLabel',
    'test' => 'inputLabelNo',
    'score' => '10',
    'level' => 'a',
    'trust' => '0.7',
    'weight' => '0.9',
    'ref' => 'H44',
    'scs' => '1.1.1,1.3.1,3.3.2,4.1.2',
    'rel' => 'H71',
    'wcag' => '3',
    'chkp' => '12.4',
    'curric' => 'sam96-0.htm',
    'prio' => 'AA',
  ),
  'input_03' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'inputAltNo',
    'score' => '5',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'ref' => 'H36',
    'scs' => '1.1.1',
    'wcag' => '2',
  ),
  'justif_txt_01' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'justifiedTxt',
    'score' => '3',
    'level' => 'AAA',
    'trust' => '1',
    'weight' => '0.1',
    'top' => '1',
    'steps' => '1',
    'ref' => 'F88',
    'scs' => '1.4.8',
    'rel' => 'G169',
    'wcag' => '2',
  ),
  'justif_txt_02' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'justifiedCss',
    'score' => '3',
    'level' => 'AAA',
    'trust' => '0.9',
    'weight' => '0.1',
    'top' => '1',
    'steps' => '1',
    'ref' => 'C19',
    'scs' => '1.4.8',
    'wcag' => '2',
  ),
  'label_01' =>
  array (
    'type' => 'prop',
    'elem' => 'label',
    'test' => 'labelForNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'ref' => 'F68',
    'scs' => '1.3.1,4.1.2',
    'rel' => 'H44',
    'wcag' => '3',
    'chkp' => '12.4',
    'curric' => 'sam96-0.htm',
    'prio' => 'AA',
  ),
  'label_02' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'labelPosNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'top' => '1',
    'steps' => '1',
    'ref' => 'G162',
    'scs' => '1.3.1,3.3.2',
    'wcag' => '2',
  ),
  'label_03' =>
  array (
    'type' => 'prop',
    'elem' => 'label',
    'test' => 'labelTextNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F68',
    'scs' => '1.3.1,4.1.2',
    'wcag' => '2',
  ),
  'lang_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'lang',
    'score' => '10',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'ref' => 'H57',
    'scs' => '3.1.1',
    'rel' => 'H58',
    'wcag' => '3',
    'chkp' => '4.3',
    'curric' => 'sam42-0.htm',
    'prio' => 'AAA',
  ),
  'lang_02' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'langCodeNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H57',
    'scs' => '3.1.1',
    'rel' => 'H58',
    'wcag' => '3',
    'chkp' => '4.3',
    'curric' => 'sam42-0.htm',
    'prio' => 'AAA',
  ),
  'lang_03' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'langNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H57',
    'scs' => '3.1.1',
    'rel' => 'H58',
    'wcag' => '3',
    'chkp' => '4.3',
    'curric' => 'sam42-0.htm',
    'prio' => 'AAA',
  ),
  'lang_04' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'langMatchNo',
    'score' => '4',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H57',
    'scs' => '3.1.1',
    'rel' => 'H58',
    'wcag' => '3',
    'chkp' => '4.3',
    'curric' => 'sam42-0.htm',
    'prio' => 'AAA',
  ),
  'lang_05' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'langExtra',
    'score' => '5',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H57',
    'scs' => '3.1.1',
    'rel' => 'H58',
    'wcag' => '3',
    'chkp' => '4.3',
    'curric' => 'sam42-0.htm',
    'prio' => 'AAA',
  ),
  'layout_01a' =>
  array (
    'type' => 'fals',
    'elem' => 'all',
    'test' => 'layoutElem',
    'score' => '10',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'ref' => 'G115',
    'scs' => '1.3.1',
    'rel' => 'H49',
    'wcag' => '3',
    'chkp' => '3.3',
    'curric' => 'sam30-0.htm',
    'prio' => 'AA',
  ),
  'layout_01b' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'layoutElem',
    'score' => '5',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'top' => '2',
    'steps' => '2',
    'ref' => 'G115',
    'scs' => '1.3.1',
    'rel' => 'H49',
    'wcag' => '3',
    'chkp' => '3.3',
    'curric' => 'sam30-0.htm',
    'prio' => 'AA',
  ),
  'layout_02a' =>
  array (
    'type' => 'fals',
    'elem' => 'all',
    'test' => 'layoutAttr',
    'score' => '10',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'ref' => 'G140',
    'scs' => '1.3.1,1.4.5,1.4.9',
    'wcag' => '3',
    'chkp' => '3.3',
    'curric' => 'sam30-0.htm',
    'prio' => 'AA',
  ),
  'layout_02b' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'layoutAttr',
    'score' => '5',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'top' => '3',
    'steps' => '3',
    'ref' => 'G140',
    'scs' => '1.3.1,1.4.5,1.4.9',
    'wcag' => '3',
    'chkp' => '3.3',
    'curric' => 'sam30-0.htm',
    'prio' => 'AA',
  ),
  'layout_03' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'layoutFixed',
    'score' => '5',
    'level' => 'aa',
    'trust' => '1',
    'weight' => '0.5',
    'top' => '1',
    'steps' => '1',
    'ref' => 'G146',
    'scs' => '1.4.4,1.4.8',
    'wcag' => '2',
  ),
  'link_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'linkRel',
    'score' => '10',
    'level' => 'aa',
    'trust' => '0.9',
    'weight' => '0.4',
    'ref' => 'H59',
    'scs' => '2.4.5,2.4.8',
    'rel' => 'G127',
    'wcag' => '3',
    'chkp' => '13.9',
    'curric' => 'sam111-0.htm',
    'prio' => 'aaa',
  ),
  'list_01' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'liNoList',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'top' => '3',
    'steps' => '3',
    'ref' => 'H48',
    'scs' => '1.3.1',
    'wcag' => '3',
    'chkp' => '3.6',
    'curric' => 'sam35-0.htm',
    'prio' => 'AA',
  ),
  'long_01' =>
  array (
    'type' => 'prop',
    'elem' => 'longDImg',
    'test' => 'longDNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H45',
    'scs' => '1.1.1',
    'rel' => 'F67',
    'wcag' => '2',
  ),
  'marquee_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'marquee',
    'score' => '1',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F16',
    'scs' => '2.2.2',
    'wcag' => '3',
    'chkp' => '7.3',
    'curric' => 'sam62-0.htm',
    'prio' => 'aa',
  ),
  'meta_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'metaRefresh',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'ref' => 'F41',
    'scs' => '2.2.1,2.2.4,3.2.5',
    'rel' => 'SVR1',
    'wcag' => '3',
    'chkp' => '7.4',
    'curric' => 'sam63-0.htm',
    'prio' => 'aa',
  ),
  'meta_02' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'metaRedir',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '1',
    'ref' => 'F40',
    'scs' => '2.2.1,2.2.4',
    'wcag' => '3',
    'chkp' => '7.5',
    'curric' => 'sam64-0.htm',
    'prio' => 'aa',
  ),
  'noframes_01' =>
  array (
    'type' => 'fals',
    'elem' => 'frame',
    'test' => 'noframes',
    'score' => '3',
    'level' => 'AA',
    'trust' => '1',
    'weight' => '0.5',
    'wcag' => '1',
    'chkp' => '12.2',
    'curric' => 'sam92-0.htm',
    'prio' => 'AA',
  ),
  'noscript' =>
  array (
    'type' => 'decr',
    'elem' => 'scriptBody',
    'test' => 'noscripts',
    'score' => '4',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'top' => '1',
    'wcag' => '1',
    'chkp' => '1.1',
    'curric' => 'sam12-0.htm',
    'prio' => 'A',
    'steps' => '1',
  ),
  'object_01' =>
  array (
    'type' => 'prop',
    'elem' => 'object',
    'test' => 'objectAltNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H27',
    'scs' => '1.1.1',
    'rel' => 'H53',
    'wcag' => '2',
  ),
  'scope_01' =>
  array (
    'type' => 'decr',
    'elem' => 'table',
    'test' => 'scopeNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'top' => '1',
    'steps' => '1',
    'ref' => 'H63',
    'scs' => '1.3.1',
    'wcag' => '2',
  ),
  'table_01' =>
  array (
    'type' => 'prop',
    'elem' => 'tableLayout',
    'test' => 'tableLayoutCaption',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F46',
    'scs' => '1.3.1',
    'rel' => 'H51,H39,H73',
    'wcag' => '3',
    'chkp' => '5.5',
    'curric' => 'sam50-0.htm',
    'prio' => 'AAA',
  ),
  'table_02' =>
  array (
    'type' => 'prop',
    'elem' => 'tableData',
    'test' => 'tableDataCaption',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H39',
    'scs' => '1.3.1',
    'rel' => 'H73',
    'wcag' => '3',
    'chkp' => '5.5',
    'curric' => 'sam50-0.htm',
    'prio' => 'AAA',
  ),
  'table_03' =>
  array (
    'type' => 'prop',
    'elem' => 'table',
    'test' => 'tableCaptionSummary',
    'score' => '4',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H73',
    'scs' => '1.3.1',
    'rel' => 'H39',
    'wcag' => '3',
    'chkp' => '5.5',
    'curric' => 'sam50-0.htm',
    'prio' => 'AAA',
  ),
  'table_04' =>
  array (
    'type' => 'prop',
    'elem' => 'table',
    'test' => 'tableNested',
    'score' => '3',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'ref' => 'F49',
    'scs' => '1.3.2',
    'wcag' => '2',
  ),
  'table_05a' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'tableLayout',
    'score' => '4',
    'level' => 'a',
    'trust' => '1',
    'weight' => '0.8',
    'top' => '1',
    'steps' => '1',
    'ref' => 'H51',
    'scs' => '1.3.1',
    'wcag' => '3',
    'chkp' => '5.3',
    'curric' => 'sam48-0.htm',
    'prio' => 'AA',
  ),
  'table_05b' =>
  array (
    'type' => 'fals',
    'elem' => 'table',
    'test' => 'tableLayout',
    'score' => '10',
    'level' => 'aa',
    'trust' => '1',
    'weight' => '0.8',
    'wcag' => '1',
    'chkp' => '5.3',
    'curric' => 'sam48-0.htm',
    'prio' => 'AA',
  ),
  'table_06' =>
  array (
    'type' => 'decr',
    'elem' => 'tableComplex',
    'test' => 'tableComplexError',
    'score' => '4',
    'level' => 'a',
    'trust' => '0.8',
    'weight' => '0.8',
    'top' => '1',
    'steps' => '1',
    'ref' => 'H43',
    'scs' => '1.3.1',
    'rel' => 'H63',
    'wcag' => '2',
  ),
  'title_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'titleVrs',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H25',
    'scs' => '2.4.2',
    'rel' => 'G88',
    'wcag' => '3',
    'chkp' => '13.2',
    'curric' => 'sam98-0.htm',
    'prio' => 'AA',
  ),
  'title_02' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'titleNo',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'H25',
    'scs' => '2.4.2',
    'rel' => 'G88',
    'wcag' => '3',
    'chkp' => '13.2',
    'curric' => 'sam98-0.htm',
    'prio' => 'AA',
  ),
  'title_03' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'titleNull',
    'score' => '3',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F25',
    'scs' => '2.4.2',
    'rel' => 'H25,G88',
    'wcag' => '3',
    'chkp' => '13.2',
    'curric' => 'sam98-0.htm',
    'prio' => 'AA',
  ),
  'title_04' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'titleLong',
    'score' => '10',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'top' => '64',
    'steps' => '10',
    'ref' => 'G88',
    'scs' => '2.4.2',
    'rel' => 'H25',
    'wcag' => '2',
  ),
  'title_05' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'titleChars',
    'score' => '4',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'ref' => 'G88',
    'scs' => '2.4.2',
    'rel' => 'H25',
    'wcag' => '3',
    'chkp' => '13.2',
    'curric' => 'sam98-0.htm',
    'prio' => 'AA',
  ),
  'title_06' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'titleOk',
    'score' => '10',
    'level' => 'a',
    'trust' => '0.9',
    'weight' => '0.8',
    'ref' => 'H25',
    'scs' => '2.4.2',
    'rel' => 'G88,',
    'wcag' => '3',
    'chkp' => '13.2',
    'curric' => 'sam98-0.htm',
    'prio' => 'AA',
  ),
  'title_07' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'titleSame',
    'score' => '4',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'F25',
    'scs' => '2.4.2',
    'rel' => 'H25,G88',
    'wcag' => '2',
  ),
  'values_01a' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'valueAbsHtml',
    'score' => '4',
    'level' => 'AA',
    'trust' => '0.9',
    'weight' => '0.4',
    'top' => '1',
    'steps' => '1',
    'ref' => 'G146',
    'scs' => '1.4.4',
    'wcag' => '3',
    'chkp' => '3.4',
    'curric' => 'sam32-0.htm',
    'prio' => 'AA',
  ),
  'values_01b' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'valueRelHtml',
    'score' => '10',
    'level' => 'aa',
    'trust' => '0.9',
    'weight' => '0.4',
    'ref' => 'G146',
    'scs' => '1.4.4',
    'wcag' => '3',
    'chkp' => '3.4',
    'curric' => 'sam32-0.htm',
    'prio' => 'AA',
  ),
  'values_02a' =>
  array (
    'type' => 'decr',
    'elem' => 'all',
    'test' => 'valueAbsCss',
    'score' => '3',
    'level' => 'AAA',
    'trust' => '0.9',
    'weight' => '0.1',
    'top' => '1',
    'steps' => '1',
    'ref' => 'C24',
    'scs' => '1.4.8',
    'rel' => 'C20',
    'wcag' => '3',
    'chkp' => '3.4',
    'curric' => 'sam32-0.htm',
    'prio' => 'AA',
  ),
  'values_02b' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'valueRelCss',
    'score' => '10',
    'level' => 'aaa',
    'trust' => '1',
    'weight' => '0.1',
    'ref' => 'C24',
    'scs' => '1.4.8',
    'rel' => 'C20',
    'wcag' => '3',
    'chkp' => '3.4',
    'curric' => 'sam32-0.htm',
    'prio' => 'AA',
  ),
  'w3c_validator_01a' =>
  array (
    'type' => 'fals',
    'elem' => 'w3cValidator',
    'test' => 'w3cValidatorErrors',
    'score' => '10',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'ref' => 'G134',
    'scs' => '4.1.1',
    'wcag' => '3',
    'chkp' => '3.2',
    'curric' => 'sam29-0.htm',
    'prio' => 'AA',
  ),
  'w3c_validator_01b' =>
  array (
    'type' => 'decr',
    'elem' => 'w3cValidator',
    'test' => 'w3cValidatorErrors',
    'score' => '5',
    'level' => 'A',
    'trust' => '1',
    'weight' => '0.9',
    'top' => '10',
    'steps' => '10',
    'ref' => 'G134',
    'scs' => '4.1.1',
    'wcag' => '3',
    'chkp' => '3.2',
    'curric' => 'sam29-0.htm',
    'prio' => 'AA',
  ),
  'win_01' =>
  array (
    'type' => 'true',
    'elem' => 'all',
    'test' => 'newWinOnLoad',
    'score' => '3',
    'level' => 'A',
    'trust' => '0.9',
    'weight' => '0.9',
    'ref' => 'F52',
    'scs' => '3.2.1',
    'wcag' => '2',
  ),
);
?>